# Generated by Django 5.2.6 on 2025-09-23 19:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_category_user_email_verified_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('29.99'), help_text='Monthly subscription fee', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='External payment method used', max_length=100)),
                ('payment_reference', models.CharField(blank=True, help_text='External payment reference/transaction ID', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about payment status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='hostel',
            name='google_location_link',
            field=models.URLField(blank=True, help_text='Google Maps location link', max_length=500),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured hostels appear first in search results and on homepage'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='landmark_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from landmark in kilometers', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='nearby_landmark',
            field=models.CharField(blank=True, help_text='Name of nearby university, school, or workplace', max_length=300),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['is_featured'], name='hostels_hos_is_feat_a5c963_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['landmark_distance'], name='hostels_hos_landmar_b736a3_idx'),
        ),
        migrations.AddField(
            model_name='hostelsubscription',
            name='hostel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='hostels.hostel'),
        ),
    ]
