# Generated by Django 5.2.6 on 2025-09-23 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostelsubscription_alter_hostel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelsubscription',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('8999.00'), help_text='Monthly subscription fee (PKR)', max_digits=10),
        ),
    ]
