# Generated by Django 5.2.6 on 2025-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_alter_hostelsubscription_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='gender_type',
            field=models.CharField(choices=[('male', 'Boys/Men Only'), ('female', 'Girls/Women Only'), ('mixed', 'Co-ed/Mixed')], default='mixed', help_text='Who can stay at this hostel', max_length=10),
        ),
    ]
