# Generated by Django 5.2.6 on 2025-10-05 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_hostel_gender_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('duration_type', models.CharField(choices=[('1_day', '1 Day'), ('1_week', '1 Week'), ('1_month', '1 Month')], max_length=20, unique=True)),
                ('duration_days', models.IntegerField(help_text='Number of days for this plan')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Benefits and features of this plan')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['duration_days'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='How payment was made', max_length=100)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference', max_length=200)),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Screenshot or receipt of payment', upload_to='payment_screenshots/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('featured_start_date', models.DateTimeField(blank=True, null=True)),
                ('featured_end_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_requests', to='hostels.hostel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_requests', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hostels.featuredplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_featured_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('views_during_period', models.IntegerField(default=0)),
                ('contacts_revealed_during_period', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_history', to='hostels.hostel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.featuredplan')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hostels.featuredrequest')),
            ],
            options={
                'verbose_name_plural': 'Featured histories',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='featuredrequest',
            index=models.Index(fields=['status'], name='hostels_fea_status_46acae_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredrequest',
            index=models.Index(fields=['featured_start_date', 'featured_end_date'], name='hostels_fea_feature_6a7208_idx'),
        ),
    ]
